config/routes.rb
Rails.application.routes.draw do
  #root 'tasks#index'
  root 'contacts#index'
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all
  	@contact = Contact.new
  end

  def new
  	@contact = Contact.new
  end

  def create
    Contact.create(contact_params)
    redirect_to root_path
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :company, :title)
  end

end

app/controllers/tasks_controller.rb
require 'uri'

class TasksController < ApplicationController

	def index
		@input = "http://www.google.com:80/search?q=kittens&lang=en"
		uri = URI.parse(@input)
		@hash = Hash.new
		@hash = {"scheme"=>uri.scheme, "host"=>uri.host, 
			"path"=>uri.path, "port"=>uri.port, "query"=>uri.query}
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/contacts/index.html.erb
<div class="header text-center">
  <h1>Contact List</h1>
</div>

<!--<%= link_to 'New Contacct', new_contact_path, class: 'nav-link' %>-->

<div class="booyah-box col-10 offset-1">
  <h2>Enter Contact Information</h1>
  <%= simple_form_for @contact do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :company %>
    <%= f.input :title %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

<br /><br />

<div class="container-fluid">
  <div class="row">
		<% @contacts.each do |contact| %>
    <div class="col-md-2 col-lg-1  offset-1">
	    <%= contact.first_name %> <%= contact.last_name %><br />
	    <%= contact.company %><br />
	    <%= contact.title %><br /><br />
    </div>
		<% end %>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Contact Information</h1>
  <%= simple_form_for @contact do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :company %>
    <%= f.input :title %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Task</h1>

<p>url = <%= @input %>
<p>hash = <%= @hash %>